{
 "cells": [
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 객체\n",
    "asyncio는 4가지 중요한 객체를 가지고 있다. 그 객체들은 다음과 같다.\n",
    "1. coroutine\n",
    "\n",
    "2. future\n",
    "\n",
    "3. task\n",
    "\n",
    "4. event_loop"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### coroutine 구조"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "#cpython/Lib/_collections_abc.py\n",
    "from abc import ABCMeta, abstractmethod\n",
    "\n",
    "GenericAlias = type(list[int])\n",
    "def _check_methods(C, *methods):\n",
    "    mro = C.__mro__\n",
    "    for method in methods:\n",
    "        for B in mro:\n",
    "            if method in B.__dict__:\n",
    "                if B.__dict__[method] is None:\n",
    "                    return NotImplemented\n",
    "                break\n",
    "        else:\n",
    "            return NotImplemented\n",
    "    return True\n",
    "\n",
    "class Awaitable(metaclass=ABCMeta):\n",
    "\n",
    "    __slots__ = ()\n",
    "\n",
    "    @abstractmethod\n",
    "    def __await__(self):\n",
    "        yield\n",
    "\n",
    "    @classmethod\n",
    "    def __subclasshook__(cls, C):\n",
    "        if cls is Awaitable:\n",
    "            return _check_methods(C, \"__await__\")\n",
    "        return NotImplemented\n",
    "\n",
    "    __class_getitem__ = classmethod(GenericAlias)\n",
    "\n",
    "\n",
    "class Coroutine(Awaitable):\n",
    "\n",
    "    __slots__ = ()\n",
    "\n",
    "    @abstractmethod\n",
    "    def send(self, value):\n",
    "        \"\"\"Send a value into the coroutine.\n",
    "        Return next yielded value or raise StopIteration.\n",
    "        \"\"\"\n",
    "        raise StopIteration\n",
    "\n",
    "    @abstractmethod\n",
    "    def throw(self, typ, val=None, tb=None):\n",
    "        \"\"\"Raise an exception in the coroutine.\n",
    "        Return next yielded value or raise StopIteration.\n",
    "        \"\"\"\n",
    "        if val is None:\n",
    "            if tb is None:\n",
    "                raise typ\n",
    "            val = typ()\n",
    "        if tb is not None:\n",
    "            val = val.with_traceback(tb)\n",
    "        raise val\n",
    "\n",
    "    def close(self):\n",
    "        \"\"\"Raise GeneratorExit inside coroutine.\n",
    "        \"\"\"\n",
    "        try:\n",
    "            self.throw(GeneratorExit)\n",
    "        except (GeneratorExit, StopIteration):\n",
    "            pass\n",
    "        else:\n",
    "            raise RuntimeError(\"coroutine ignored GeneratorExit\")\n",
    "\n",
    "    @classmethod\n",
    "    def __subclasshook__(cls, C):\n",
    "        if cls is Coroutine:\n",
    "            return _check_methods(C, '__await__', 'send', 'throw', 'close')\n",
    "        return NotImplemented"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### future 구조"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "ename": "ImportError",
     "evalue": "attempted relative import with no known parent package",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mImportError\u001b[0m                               Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[8], line 3\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[39mimport\u001b[39;00m \u001b[39msys\u001b[39;00m\n\u001b[1;32m      2\u001b[0m \u001b[39mimport\u001b[39;00m \u001b[39mevents\u001b[39;00m\n\u001b[0;32m----> 3\u001b[0m \u001b[39mimport\u001b[39;00m \u001b[39mbase_futures\u001b[39;00m\n\u001b[1;32m      4\u001b[0m \u001b[39mimport\u001b[39;00m \u001b[39mformat_helpers\u001b[39;00m\n\u001b[1;32m      5\u001b[0m \u001b[39mimport\u001b[39;00m \u001b[39mexceptions\u001b[39;00m\n",
      "File \u001b[0;32m~/fun/asyncio_study/base_futures.py:5\u001b[0m\n\u001b[1;32m      1\u001b[0m __all__ \u001b[39m=\u001b[39m ()\n\u001b[1;32m      3\u001b[0m \u001b[39mimport\u001b[39;00m \u001b[39mreprlib\u001b[39;00m\n\u001b[0;32m----> 5\u001b[0m \u001b[39mimport\u001b[39;00m \u001b[39mformat_helpers\u001b[39;00m\n\u001b[1;32m      7\u001b[0m \u001b[39m# States for Future.\u001b[39;00m\n\u001b[1;32m      8\u001b[0m _PENDING \u001b[39m=\u001b[39m \u001b[39m'\u001b[39m\u001b[39mPENDING\u001b[39m\u001b[39m'\u001b[39m\n",
      "File \u001b[0;32m~/fun/asyncio_study/format_helpers.py:7\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[39mimport\u001b[39;00m \u001b[39msys\u001b[39;00m\n\u001b[1;32m      5\u001b[0m \u001b[39mimport\u001b[39;00m \u001b[39mtraceback\u001b[39;00m\n\u001b[0;32m----> 7\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39m.\u001b[39;00m \u001b[39mimport\u001b[39;00m constants\n\u001b[1;32m     10\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39m_get_function_source\u001b[39m(func):\n\u001b[1;32m     11\u001b[0m     func \u001b[39m=\u001b[39m inspect\u001b[39m.\u001b[39munwrap(func)\n",
      "\u001b[0;31mImportError\u001b[0m: attempted relative import with no known parent package"
     ]
    }
   ],
   "source": [
    "import sys\n",
    "import events\n",
    "import base_futures\n",
    "import format_helpers\n",
    "import exceptions\n",
    "import contextvars\n",
    "_PENDING = base_futures._PENDING\n",
    "_CANCELLED = base_futures._CANCELLED\n",
    "_FINISHED = base_futures._FINISHED\n",
    "\n",
    "class Future:\n",
    "    \"\"\"This class is *almost* compatible with concurrent.futures.Future.\n",
    "\n",
    "    Differences:\n",
    "\n",
    "    - This class is not thread-safe.\n",
    "\n",
    "    - result() and exception() do not take a timeout argument and\n",
    "      raise an exception when the future isn't done yet.\n",
    "\n",
    "    - Callbacks registered with add_done_callback() are always called\n",
    "      via the event loop's call_soon().\n",
    "\n",
    "    - This class is not compatible with the wait() and as_completed()\n",
    "      methods in the concurrent.futures package.\n",
    "\n",
    "    (In Python 3.4 or later we may be able to unify the implementations.)\n",
    "    \"\"\"\n",
    "\n",
    "    # Class variables serving as defaults for instance variables.\n",
    "    _state = _PENDING\n",
    "    _result = None\n",
    "    _exception = None\n",
    "    _loop = None\n",
    "    _source_traceback = None\n",
    "    _cancel_message = None\n",
    "    # A saved CancelledError for later chaining as an exception context.\n",
    "    _cancelled_exc = None\n",
    "\n",
    "    # This field is used for a dual purpose:\n",
    "    # - Its presence is a marker to declare that a class implements\n",
    "    #   the Future protocol (i.e. is intended to be duck-type compatible).\n",
    "    #   The value must also be not-None, to enable a subclass to declare\n",
    "    #   that it is not compatible by setting this to None.\n",
    "    # - It is set by __iter__() below so that Task._step() can tell\n",
    "    #   the difference between\n",
    "    #   `await Future()` or`yield from Future()` (correct) vs.\n",
    "    #   `yield Future()` (incorrect).\n",
    "    _asyncio_future_blocking = False\n",
    "\n",
    "    __log_traceback = False\n",
    "\n",
    "    def __init__(self, *, loop=None):\n",
    "        \"\"\"Initialize the future.\n",
    "\n",
    "        The optional event_loop argument allows explicitly setting the event\n",
    "        loop object used by the future. If it's not provided, the future uses\n",
    "        the default event loop.\n",
    "        \"\"\"\n",
    "        if loop is None:\n",
    "            self._loop = events.get_event_loop()\n",
    "        else:\n",
    "            self._loop = loop\n",
    "        self._callbacks = []\n",
    "        if self._loop.get_debug():\n",
    "            self._source_traceback = format_helpers.extract_stack(\n",
    "                sys._getframe(1))\n",
    "\n",
    "    def __repr__(self):\n",
    "        return base_futures._future_repr(self)\n",
    "\n",
    "    def __del__(self):\n",
    "        if not self.__log_traceback:\n",
    "            # set_exception() was not called, or result() or exception()\n",
    "            # has consumed the exception\n",
    "            return\n",
    "        exc = self._exception\n",
    "        context = {\n",
    "            'message':\n",
    "                f'{self.__class__.__name__} exception was never retrieved',\n",
    "            'exception': exc,\n",
    "            'future': self,\n",
    "        }\n",
    "        if self._source_traceback:\n",
    "            context['source_traceback'] = self._source_traceback\n",
    "        self._loop.call_exception_handler(context)\n",
    "\n",
    "    __class_getitem__ = classmethod(GenericAlias)\n",
    "\n",
    "    @property\n",
    "    def _log_traceback(self):\n",
    "        return self.__log_traceback\n",
    "\n",
    "    @_log_traceback.setter\n",
    "    def _log_traceback(self, val):\n",
    "        if val:\n",
    "            raise ValueError('_log_traceback can only be set to False')\n",
    "        self.__log_traceback = False\n",
    "\n",
    "    def get_loop(self):\n",
    "        \"\"\"Return the event loop the Future is bound to.\"\"\"\n",
    "        loop = self._loop\n",
    "        if loop is None:\n",
    "            raise RuntimeError(\"Future object is not initialized.\")\n",
    "        return loop\n",
    "\n",
    "    def _make_cancelled_error(self):\n",
    "        \"\"\"Create the CancelledError to raise if the Future is cancelled.\n",
    "\n",
    "        This should only be called once when handling a cancellation since\n",
    "        it erases the saved context exception value.\n",
    "        \"\"\"\n",
    "        if self._cancelled_exc is not None:\n",
    "            exc = self._cancelled_exc\n",
    "            self._cancelled_exc = None\n",
    "            return exc\n",
    "\n",
    "        if self._cancel_message is None:\n",
    "            exc = exceptions.CancelledError()\n",
    "        else:\n",
    "            exc = exceptions.CancelledError(self._cancel_message)\n",
    "        return exc\n",
    "\n",
    "    def cancel(self, msg=None):\n",
    "        \"\"\"Cancel the future and schedule callbacks.\n",
    "\n",
    "        If the future is already done or cancelled, return False.  Otherwise,\n",
    "        change the future's state to cancelled, schedule the callbacks and\n",
    "        return True.\n",
    "        \"\"\"\n",
    "        self.__log_traceback = False\n",
    "        if self._state != _PENDING:\n",
    "            return False\n",
    "        self._state = _CANCELLED\n",
    "        self._cancel_message = msg\n",
    "        self.__schedule_callbacks()\n",
    "        return True\n",
    "\n",
    "    def __schedule_callbacks(self):\n",
    "        \"\"\"Internal: Ask the event loop to call all callbacks.\n",
    "\n",
    "        The callbacks are scheduled to be called as soon as possible. Also\n",
    "        clears the callback list.\n",
    "        \"\"\"\n",
    "        callbacks = self._callbacks[:]\n",
    "        if not callbacks:\n",
    "            return\n",
    "\n",
    "        self._callbacks[:] = []\n",
    "        for callback, ctx in callbacks:\n",
    "            self._loop.call_soon(callback, self, context=ctx)\n",
    "\n",
    "    def cancelled(self):\n",
    "        \"\"\"Return True if the future was cancelled.\"\"\"\n",
    "        return self._state == _CANCELLED\n",
    "\n",
    "    # Don't implement running(); see http://bugs.python.org/issue18699\n",
    "\n",
    "    def done(self):\n",
    "        \"\"\"Return True if the future is done.\n",
    "\n",
    "        Done means either that a result / exception are available, or that the\n",
    "        future was cancelled.\n",
    "        \"\"\"\n",
    "        return self._state != _PENDING\n",
    "\n",
    "    def result(self):\n",
    "        \"\"\"Return the result this future represents.\n",
    "\n",
    "        If the future has been cancelled, raises CancelledError.  If the\n",
    "        future's result isn't yet available, raises InvalidStateError.  If\n",
    "        the future is done and has an exception set, this exception is raised.\n",
    "        \"\"\"\n",
    "        if self._state == _CANCELLED:\n",
    "            exc = self._make_cancelled_error()\n",
    "            raise exc\n",
    "        if self._state != _FINISHED:\n",
    "            raise exceptions.InvalidStateError('Result is not ready.')\n",
    "        self.__log_traceback = False\n",
    "        if self._exception is not None:\n",
    "            raise self._exception.with_traceback(self._exception_tb)\n",
    "        return self._result\n",
    "\n",
    "    def exception(self):\n",
    "        \"\"\"Return the exception that was set on this future.\n",
    "\n",
    "        The exception (or None if no exception was set) is returned only if\n",
    "        the future is done.  If the future has been cancelled, raises\n",
    "        CancelledError.  If the future isn't done yet, raises\n",
    "        InvalidStateError.\n",
    "        \"\"\"\n",
    "        if self._state == _CANCELLED:\n",
    "            exc = self._make_cancelled_error()\n",
    "            raise exc\n",
    "        if self._state != _FINISHED:\n",
    "            raise exceptions.InvalidStateError('Exception is not set.')\n",
    "        self.__log_traceback = False\n",
    "        return self._exception\n",
    "\n",
    "    def add_done_callback(self, fn, *, context=None):\n",
    "        \"\"\"Add a callback to be run when the future becomes done.\n",
    "\n",
    "        The callback is called with a single argument - the future object. If\n",
    "        the future is already done when this is called, the callback is\n",
    "        scheduled with call_soon.\n",
    "        \"\"\"\n",
    "        if self._state != _PENDING:\n",
    "            self._loop.call_soon(fn, self, context=context)\n",
    "        else:\n",
    "            if context is None:\n",
    "                context = contextvars.copy_context()\n",
    "            self._callbacks.append((fn, context))\n",
    "\n",
    "    # New method not in PEP 3148.\n",
    "\n",
    "    def remove_done_callback(self, fn):\n",
    "        \"\"\"Remove all instances of a callback from the \"call when done\" list.\n",
    "\n",
    "        Returns the number of callbacks removed.\n",
    "        \"\"\"\n",
    "        filtered_callbacks = [(f, ctx)\n",
    "                              for (f, ctx) in self._callbacks\n",
    "                              if f != fn]\n",
    "        removed_count = len(self._callbacks) - len(filtered_callbacks)\n",
    "        if removed_count:\n",
    "            self._callbacks[:] = filtered_callbacks\n",
    "        return removed_count\n",
    "\n",
    "    # So-called internal methods (note: no set_running_or_notify_cancel()).\n",
    "\n",
    "    def set_result(self, result):\n",
    "        \"\"\"Mark the future done and set its result.\n",
    "\n",
    "        If the future is already done when this method is called, raises\n",
    "        InvalidStateError.\n",
    "        \"\"\"\n",
    "        if self._state != _PENDING:\n",
    "            raise exceptions.InvalidStateError(f'{self._state}: {self!r}')\n",
    "        self._result = result\n",
    "        self._state = _FINISHED\n",
    "        self.__schedule_callbacks()\n",
    "\n",
    "    def set_exception(self, exception):\n",
    "        \"\"\"Mark the future done and set an exception.\n",
    "\n",
    "        If the future is already done when this method is called, raises\n",
    "        InvalidStateError.\n",
    "        \"\"\"\n",
    "        if self._state != _PENDING:\n",
    "            raise exceptions.InvalidStateError(f'{self._state}: {self!r}')\n",
    "        if isinstance(exception, type):\n",
    "            exception = exception()\n",
    "        if isinstance(exception, StopIteration):\n",
    "            new_exc = RuntimeError(\"StopIteration interacts badly with \"\n",
    "                                   \"generators and cannot be raised into a \"\n",
    "                                   \"Future\")\n",
    "            new_exc.__cause__ = exception\n",
    "            new_exc.__context__ = exception\n",
    "            exception = new_exc\n",
    "        self._exception = exception\n",
    "        self._exception_tb = exception.__traceback__\n",
    "        self._state = _FINISHED\n",
    "        self.__schedule_callbacks()\n",
    "        self.__log_traceback = True\n",
    "\n",
    "    def __await__(self):\n",
    "        if not self.done():\n",
    "            self._asyncio_future_blocking = True\n",
    "            yield self  # This tells Task to wait for completion.\n",
    "        if not self.done():\n",
    "            raise RuntimeError(\"await wasn't used with future\")\n",
    "        return self.result()  # May raise too.\n",
    "\n",
    "    __iter__ = __await__  # make compatible with 'yield from'.\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.3"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
